version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 5
  versioning-strategy: increase
  commit-message:
    prefix: build
    include: scope
  ignore:
    - dependency-name: "husky"