name: CD
on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          registry-url: https://registry.npmjs.org/
      
      - name: Install dependencies
        run: npm ci --ignore-scripts
      
      - name: Check formatting
        run: npm run prettier:check
      
      - name: Lint check
        run: npm run lint:check
      
      - name: Run tests
        run: npm run test:ci
      
      - name: Build package
        run: npm run build
      
      - name: Copy files
        run: |
          cp LICENSE build/LICENSE
          cp README.md build/README.md
      
      - name: Prepare package.json
        run: |
          jq 'del(.devDependencies) | del(.scripts) | del(.files)' package.json > build/package.json
          cat build/package.json
      - name: Fix package.json
        run: npm pkg fix --location=./build
      
      - name: Setup .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH_TOKEN }}" > .npmrc
          ls -al
          cat ./.npmrc
          
      - name: Verify build directory content
        run: ls -al build

      - name: Publish package
        run: npm publish ./build
      
        env:
          NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
